name: colomney_lints
description: Personalized lint rules used by colomney.
version: 0.0.4
homepage: https://github.com/shotaIDE/ColomneyFlutterLints

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.1.0
